version: 1.0.{build}
clone_depth: 5
clone_folder: c:\gopath\src\github.com\gobuffalo\buffalo

environment:
  GOPATH: c:\gopath
  matrix:
  - GOBIN: c:\go
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - GOBIN: c:\go18
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

services:
- mysql
- postgresql
install:
- cmd: >-
    choco install mingw

    set PATH=%GOPATH%\bin;%GOBIN%\bin;c:\tools\mingw64\bin;%PATH%

    echo %PATH%

    echo %GOPATH%

    go version

    go env
build:
  verbosity: normal
before_build:
- cmd: go get -v -t ./...
build_script:
- cmd: go install -v github.com/gobuffalo/buffalo/buffalo
test_script:
- cmd: for /f "" %%G in ('go list github.com/gobuffalo/buffalo/... ^| find /i /v "/vendor/"') do ( go test %%G & IF ERRORLEVEL == 1 EXIT 1)
