development:
  dialect: postgres
  database: hello_world_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: hello_world_test
  user: postgres
  password: postgres
  host: 127.0.0.1

production:
  dialect: postgres
  database: hello_world_production
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 25